### ISSUE TITLE
fetch_dataset not working

### ISSUE THREAD

**Issue by jbannon** [ysig/GraKeL#105]
In trying to run the example code on building a pipeline, here: [example](https://ysig.github.io/GraKeL/0.1a8/auto_examples/plot_pipeline_example.html#sphx-glr-auto-examples-plot-pipeline-example-py) I immediately run in to an issue with urllib. Specifically, calling:

```
from grakel.datasets import fetch_dataset

MUTAG = fetch_dataset("MUTAG", verbose=False)
G, y = MUTAG.data, MUTAG.target
``` 

gives me:

`Traceback (most recent call last):
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Users/jamesbannon/miniconda3/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Users/jamesbannon/miniconda3/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/jamesbannon/miniconda3/lib/python3.10/ssl.py", line 1062, in _create
    self._sslobj = self._context._wrap_socket(
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jamesbannon/Desktop/RCKernels/src/grakel_test.py", line 20, in <module>
    MUTAG = fetch_dataset("MUTAG", verbose=False)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/site-packages/grakel/datasets/base.py", line 466, in fetch_dataset
    _download_zip(dataset_metadata[name]["link"], name)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/site-packages/grakel/datasets/base.py", line 372, in _download_zip
    data_url = urlopen(url, context=ctx)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/jamesbannon/miniconda3/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error Cannot create a client socket with a PROTOCOL_TLS_SERVER context (_ssl.c:801)>`

**Comment by pwelke** [comment]
I am currently facing the same issue. The reason appears to be that TU Dortmund has some sort of SSL certificate troubles. A 'fix' is to download datasets via http, instead of https. I have created a pull request that does this, although I am not sure if it is good to accept it :).

You can manually change all instances of  `https://` in ```grakel/datasets/base.py``` to `http://`
