### ISSUE TITLE
something wrong using graphlet sampling

### ISSUE THREAD

**Issue by cenyk1230** [ysig/GraKeL#2]
I used graphlet kernel for graph classification, but got following error. 
Would you please help me?

Traceback (most recent call last):
  File "group_kernel.py", line 79, in <module>
    K_test = gk.transform(X_test)
  File "/home/yukuocen/py_env/lib/python2.7/site-packages/grakel-0.1a2-py2.7-linux-x86_64.egg/grakel/graph_kernels.py", line 344, in transform
    K = self.kernel_.transform(X)
  File "/home/yukuocen/py_env/lib/python2.7/site-packages/grakel-0.1a2-py2.7-linux-x86_64.egg/grakel/kernels/graphlet_sampling.py", line 247, in transform
    Y = self.parse_input(X)
  File "/home/yukuocen/py_env/lib/python2.7/site-packages/grakel-0.1a2-py2.7-linux-x86_64.egg/grakel/kernels/graphlet_sampling.py", line 439, in parse_input
    self._Y_graph_bins[j], sg):
KeyError: 1

**Comment by ysig** [comment]
Sorry for the big delay, but without knowing my notifications where turned off.
There was a variable name collision which i will remove in a big push I will do either today or tomorrow.
Let me know if the problem get's fixed.
Thanks for the feedback!

**Comment by cenyk1230** [comment]
Waiting for your push. Thanks!

**Comment by ysig** [comment]
Push .. done!
Try now and inform me if you have any errors.
Thanks!

**Comment by cenyk1230** [comment]
I have tried the graphlet kernel and it works! Thanks 👍 

BTW, the current version number is 0.1.2a, but there is still 0.1a2 in setup.py.

**Comment by ysig** [comment]
Perfect
0.1a2 is the correct. I misspelled it on the commit message.

Thanks!

**Comment by ysig** [comment]
Perfect
0.1a2 is the correct. I misspelled it on the commit message.

Thanks!
