### ISSUE TITLE
Issue with fetch_dataset and MultiscaleLaplacian kernel

### ISSUE THREAD

**Issue by fede-vaccaro** [ysig/GraKeL#36]
Hi,
I'm having some trouble with the ML kernel. Here's the code (very simple):

```
from __future__ import print_function

from grakel import kernels
from grakel.datasets import fetch_dataset
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import numpy as np

# Loads the dataset
dataset = fetch_dataset("IMDB-BINARY", produce_labels_nodes=True)
G, y = dataset.data, dataset.target

# Splits the dataset into a training and a test set
G_train, G_test, y_train, y_test = train_test_split(G, y, test_size=0.1, random_state=42)

# Uses the shortest path kernel to generate the kernel matrices
gk = kernels.MultiscaleLaplacian()
gk.fit(G_train)
K_train = gk.fit_transform(G_train)
K_test = gk.transform(G_test)

# Uses the SVM classifier to perform classification
print("Starting training")
clf = SVC(kernel="precomputed", verbose=True)
clf.fit(K_train, y_train)
y_pred = clf.predict(K_test)

# Computes and prints the classification accuracy
acc = accuracy_score(y_test, y_pred)
print("Accuracy:", str(round(acc * 100, 2)) + "%")

```

But it fails with this error: 

```
Traceback (most recent call last):
  File ".../gkernel/lib/python3.7/site-packages/grakel/kernels/multiscale_laplacian.py", line 465, in parse_input
    phi = np.array([list(phi_d[i]) for i in range(A.shape[0])])
  File ".../gkernel/lib/python3.7/site-packages/grakel/kernels/multiscale_laplacian.py", line 465, in <listcomp>
    phi = np.array([list(phi_d[i]) for i in range(A.shape[0])])
TypeError: 'int' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/sdb-seagate/graph-kernels/train.py", line 43, in <module>
    gk.fit(G_train)
  File ".../gkernel/lib/python3.7/site-packages/grakel/kernels/kernel.py", line 123, in fit
    self.X = self.parse_input(X)
  File ".../gkernel/lib/python3.7/site-packages/grakel/kernels/multiscale_laplacian.py", line 467, in parse_input
    raise TypeError('Features must be iterable and castable ' +
TypeError: Features must be iterable and castable in total to a numpy array.

```

Am I doing something wrong? Thank you for your time.

**Comment by giannisnik** [comment]
Hi @fede-vaccaro . This problem is due to the fact that the Multiscale Laplacian kernel expects the input graphs to contain node attributes and not discrete node labels. You can replace the IMDB-BINARY dataset with another dataset that contains such graphs (e.g., ENZYMES dataset) and re-run the code:

`dataset = fetch_dataset("ENZYMES", prefer_attr_nodes=True)`

To compute Multiscale Laplacian kernel on IMDB-BINARY, you need to transform manually the discrete node labels of the graphs to attributes (e.g., their one-hot representations), and then compute the kernel.
